name: 🆕 Suggest an improvement or new feature
description: ———
labels: enhancement, under discussion
body:
  - type: markdown
    attributes:
      value: |
        👋 There might be some [easy bugs](https://https://github.com/achillesrasquinha/pipupgrade/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3Abug) to tackle for new contributors.
  - type: textarea
    attributes:
      label: Description
      description: 'Please ensure your requested feature makes sense.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot
      description: You can provide screenshots/mockups to better visualize your idea. Files can be dropped in this field